### ISSUE TITLE
Test `Linear` with weight sharing

### ISSUE THREAD

**Issue by f-dangel** [plutonium-239/memsave_torch#4]
Our current implementation of `Linear` assumes that the input has shape `[batch_size, F_in]`, but `torch.nn.Linear` works with arbitrary intermediate dimensions `[batch_size, *, F_in]`. Make sure that both the forward and backward pass are correct in the presence of weight sharing.

**Comment by plutonium-239** [comment]
Added tests for 3D, 4D in https://github.com/plutonium-239/memsave_torch/commit/b016002e73050eb39f9855bb9f1ff929c108a5e9

Also in https://github.com/plutonium-239/memsave_torch/commit/b016002e73050eb39f9855bb9f1ff929c108a5e9, changed the `grad_output.t().mm(x)` in linear backward to using `grad_output.mT @ x` which works for any dimensions with/without a batch dimension at the start.

It's not possible to add tests for an arbitrary number of intermediate dimensions, but by testing it on an interactive shell with up to 10D inputs, it did not run into errors.
